### ISSUE TITLE
自己买的课怎么下载呢？

### ISSUE THREAD

**Issue by starhu521** [Lovecanon/cn_mooc_dl#1]
输入课程地址后，总是说没找到课程id
![image](https://user-images.githubusercontent.com/23275495/64145717-807ca700-ce4c-11e9-831a-de75ae03e97e.png)
分割线----------------------------------------------------------------------------------
大佬，上面是匹配问题，我改了匹配，但是下载的时候目录，文件结构都生成了，没有问题，但是下载的时候，下不下来啊
![image](https://user-images.githubusercontent.com/23275495/64148734-9727fb80-ce56-11e9-81f0-209795108578.png)

**Comment by Lovecanon** [comment]
这个课程是付费的课程，脚本现在只能下载icourse163上公开课。如果想下载简单的方法是修改替换代码中的cookies

**Comment by starhu521** [comment]
我不太懂这个python这个，请问一下，但是重试了很久之后，现在又开始下载了，但是下载的视频不能播放，格式是flv的，然后我看这个课程应该是分片的ts，不知道咱们这个处理没

**Comment by Lovecanon** [comment]
> 我不太懂这个python这个，请问一下，但是重试了很久之后，现在又开始下载了，但是下载的视频不能播放，格式是flv的，然后我看这个课程应该是分片的ts，不知道咱们这个处理没

有些课程文件的子域名从`v.stu.126.net`改成了`dvodrvfb210d.vod.126.net`，导致使用原来的域名下载失败。重试的时候会替换子域名。

可以下载flv视频？？？这是付费的课程，脚本上你没有登陆啊

网页播放器会将视频分段，通过脚本下载下来的是一个完整的文件。flv文件主流的播放器都能打开。

**Comment by Lovecanon** [comment]
> 我不太懂这个python这个，请问一下，但是重试了很久之后，现在又开始下载了，但是下载的视频不能播放，格式是flv的，然后我看这个课程应该是分片的ts，不知道咱们这个处理没

我试了一下，不登陆也可以下载。这个bug也

**Comment by starhu521** [comment]
我使用我的账号密码登录了，一开始下载一直失败重试，不知道什么时候好了，然后全部下载下来了600多个文件，显示全部成功，但是，下载下来的flv文件感觉不太对，多数只有十几兆，大的有几十兆，但是播放不了，我的播放器肯定可以播放flv的

**Comment by Lovecanon** [comment]
> 我使用我的账号密码登录了，一开始下载一直失败重试，不知道什么时候好了，然后全部下载下来了600多个文件，显示全部成功，但是，下载下来的flv文件感觉不太对，多数只有十几兆，大的有几十兆，但是播放不了，我的播放器肯定可以播放flv的

我用自带的账号登陆下载出现你这种情况，可能flv文件经过加密处理了

**Comment by starhu521** [comment]
看来应该是，感觉要搞就比较麻烦了，主要用他的网页看比较麻烦
